### ISSUE TITLE
Error `The "path" argument must be of type string.`

### ISSUE THREAD

**Issue by Philmod** [Upstatement/firestore-jest-mock#13]
# Description

I'm getting this error when I try to query a sub collection from within a function: 

```
const path = `mycol/${context.params.id}/mysubcol/${context.params.subcolId}/somethingelse`
const us = await db.collection(path).get()
```

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object

      at GrpcClient.loadProto (node_modules/@google-cloud/firestore/node_modules/google-gax/src/grpc.ts:166:23)
      at new FirestoreClient (node_modules/@google-cloud/firestore/build/src/v1/firestore_client.js:113:32)
      at ClientPool.Firestore._clientPool.pool_1.ClientPool [as clientFactory] (node_modules/@google-cloud/firestore/build/src/index.js:319:26)
      at ClientPool.acquire (node_modules/@google-cloud/firestore/build/src/pool.js:81:35)
      at ClientPool.run (node_modules/@google-cloud/firestore/build/src/pool.js:155:29)
      at _retry (node_modules/@google-cloud/firestore/build/src/index.js:918:30)
      at Firestore._retry (node_modules/@google-cloud/firestore/build/src/index.js:789:38)
```

## Steps to reproduce

NA

## Expected result

Query the mocked subcollection.

## Actual result

Error

## Environment

- OS: macos
- Nodejs version: v10.16.3
- Jest version: 25.1.0
- Browser and its version: NA
- Docker version: NA

**Comment by Philmod** [comment]
It seems to happen because I call `mockFirebase` within `describe`, after requiring the function code. By putting `mockFirebase` before the require, it fixes the problem.

**Comment by sbatson5** [comment]
@Philmod is the `require` also in that `describe` block?  The way hoisting in Jest works, a mock should technically be called first, even if you write it after your `require` as long as it is in the same `describe` block.  However, if the `requite` is outside of the describe block (or in a parent describe block) then what you are seeing is the error I would expect.  

That's an error thrown by firebase, so it would imply you are hitting the real firebase library

**Comment by sbatson5** [comment]
For reference (because I often get tripped up by hoisting with Jest): https://jestjs.io/docs/en/manual-mocks#using-with-es-module-imports

This applies to both `import` and `require` statements

**Comment by tad3j** [comment]
Try adding `testEnvironment: 'node',` to your jest config

**Comment by sbatson5** [comment]
Going to close. Feel free to reopen if you think it is related to something here
