### ISSUE TITLE
firebase-admin:  Unable to detect a Project Id in the current environment.

### ISSUE THREAD

**Issue by jor3l** [Upstatement/firestore-jest-mock#85]
# Summary
I'm trying to use this with firebase-admin, I have a `mockFirebase` with the database on it on the first describe of my tests, then with a beforeEach I call

```js
beforeEach(() => {
    admin.initializeApp({
      credential: admin.credential.cert({
        projectId: process.env.FIREBASE_PROJECT_ID,
        privateKey: process.env.FIREBASE_PRIVATE_KEY.replace(/\\n/g, '\n'),
        clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      }),
      databaseURL: process.env.FIREBASE_DATABASE_URL,
    })
  })
 ```
 
 For some reason, when my function tries to call firebase, I get the following error:
 
 ```shell
 Unable to detect a Project Id in the current environment. 
    To learn more about authentication and Google APIs, visit: 
    https://cloud.google.com/docs/authentication/getting-started
at node_modules/google-gax/node_modules/google-auth-library/build/src/auth/googleauth.js:87:31
  Caused by: Error: 
  at CollectionReference._get (node_modules/@google-cloud/firestore/build/src/reference.js:1449:23)
  at CollectionReference.get (node_modules/@google-cloud/firestore/build/src/reference.js:1438:21)
 ```
 
 Any ideas of what I'm missing for my firebase to mock properly?

**Comment by jor3l** [comment]
Also getting this

```js
console.info
      Module firebase not found, mocking skipped.

      at mockModuleIfFound (node_modules/firestore-jest-mock/mocks/firebase.js:46:13)
 ```

**Comment by jor3l** [comment]
Problem was, I had already imported my firestore class before doing the mock, I'm now importing firestore on each test and is getting the mocked version instead.
